version: '3.9'

services:
  php-fpm:
    container_name: php-fpm
    restart: unless-stopped
    build:
      context: .
      dockerfile: dockerfile
    ports:
      - "80:80"
      - "443:443"
      # - "9000:9000"
    volumes:
      - .:/var/www/html/php-todo
    depends_on:
      - database
    networks:
      - app

  database:
    image: postgres:14-alpine
    container_name: database
    restart: unless-stopped
    environment:
        POSTGRES_PASSWORD: secret
        POSTGRES_DB: php-pzn
    volumes:
        - ./docker/postgres_data:/var/lib/postgresql/data
    ports:
        - "54320:5432"
    networks:
        - app
    healthcheck:
        test: ["CMD", "pg_isready", "-U", "ckan"]

  # nginx:
  #   container_name: nginx-php-pzn
  #   restart: unless-stopped
  #   image: nginx:1.25.2-alpine
  #   ports:
  #     - "8080:80"
  #   volumes:
  #     - ./default.conf:/etc/nginx/conf.d/default.conf
  #     - .:/var/www/html/php-todo
  #   networks:
  #     - app

networks:
  app:
    driver: bridge