version: '3.9'

services:
  php-fpm:
    container_name: php-fpm
    restart: unless-stopped
    build:
      context: .
      dockerfile: dockerfile
    ports:
      - "8080:80"
      - "4433:443"
      # - "9000:9000"
    volumes:
      - .:/var/www/html/php-todo
    networks:
      - app

  # nginx:
  #   container_name: nginx-php-pzn
  #   restart: unless-stopped
  #   image: nginx:1.25.2-alpine
  #   ports:
  #     - "8080:80"
  #   volumes:
  #     - ./default.conf:/etc/nginx/conf.d/default.conf
  #     - .:/var/www/html/php-todo
  #   networks:
  #     - app

networks:
  app:
    driver: bridge